TalmerMaint.WebUI/Controllers/RoleAdminController.cs
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using TalmerMaint.Domain.Entities;
using TalmerMaint.WebUI.Infrastructure;
using System.Collections.Generic;
using TalmerMaint.WebUI.Models;

namespace TalmerMaint.WebUI.Controllers
{
    [Authorize(Roles = "UserAdmin")]
    public class RoleAdminController : Controller
    {
        // GET: RoleAdmin
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create([Required]string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = RoleManager.Create(new AppRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            return View(name);
        }

        [HttpPost]
        public ActionResult Delete(string id)
        {
            AppRole role = RoleManager.FindById(id);
            if(role != null)
            {
                IdentityResult result = RoleManager.Delete(role);
                if (result.Succeeded)
                {
                    TempData["message"] = string.Format("{0} role was deleted", role.Name);
                }
                else
                {
                    TempData["message"] = string.Format("{0} role was not deleted", role.Name);
                }
                
            }
            else
            {
                TempData["message"] = string.Format("{0} role was not deleted", role.Name);
            }
            return View("Index", RoleManager.Roles);
        }

        public ActionResult Edit(string id)
        {
            AppRole role = RoleManager.FindById(id);
            string[] memberIds = role.Users.Select(x => x.UserId).ToArray();
            IEnumerable<AppUser> members = UserManager.Users.Where(x => memberIds.Any(y => y == x.Id));
            IEnumerable<AppUser> nonMembers = UserManager.Users.Except(members);
            return View(new RoleEditModel
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        [HttpPost]
        public ActionResult Edit(RoleModificationModel model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach(string userId in model.IdsToAdd ?? new string[] { })
                {
                    result = UserManager.AddToRole(userId, model.RoleName);
                    if (!result.Succeeded)
                    {

                        return View("Error", result.Errors);
                    }
                }
                foreach(string userId in model.IdsToDelete ?? new string[] { })
                {
                    result = UserManager.RemoveFromRole(userId, model.RoleName);
                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }
                return RedirectToAction("Index");
            }
            return View("Error", new string[] { "Role not found." });
        }

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach(string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private AppUserManager UserManager
        {
            get { return HttpContext.GetOwinContext().GetUserManager<AppUserManager>(); }
        }

        private AppRoleManager RoleManager
        {
            get { return HttpContext.GetOwinContext().GetUserManager<AppRoleManager>(); }
        }
        protected override void Dispose(bool disposing)
        {

            base.Dispose(disposing);
        }
    }
}

TalmerMaint.WebUI/Views/RoleAdmin/Create.cshtml
@model string
@{
    ViewBag.Title = "Add Role";
}

<h2>Add Role</h2>
@Html.ValidationSummary(false)

@using (Html.BeginForm())
{
    <div class="form-group">
        <label>Name</label>
        <input name="name" value="@Model" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
    @Html.ActionLink("Cancel", "Index", null, new { @class="btn btn-default"})
}

TalmerMaint.WebUI/Views/RoleAdmin/Edit.cshtml
@using TalmerMaint.WebUI.Models
@using TalmerMaint.Domain.Entities
@model RoleEditModel
@{
    ViewBag.Title = "Edit Role";
}

<h2>Edit Role</h2>
@Html.ValidationSummary()
@using (Html.BeginForm())
{
    <input type="hidden" name="roleName" value="@Model.Role.Name" />
    <div class="panel panel-primary">
        <div class="panel-heading">Add To @Model.Role.Name</div>
        <table class="table table-striped">
            @if (Model.NonMembers.Count() == 0)
            {
                <tr><td colspan="2">All Users Are Members</td></tr>
            }
            else
            {
                <tr><td>Name</td><td>Add To Role</td></tr>
                foreach (AppUser user in Model.NonMembers)
                {
                    <tr>
                        <td>@user.UserName</td>
                        <td>
                            <input type="checkbox" name="IdsToAdd" value="@user.Id" />
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">Remove from @Model.Role.Name</div>
        <table class="table table-striped">
           @if (Model.Members.Count() == 0)
           {
            <tr><td colspan="2">No Users Are Members</td></tr>
           }
           else
           {
               <tr><td>Name</td><td>Remove From Role</td></tr>
            foreach (AppUser user in Model.Members)
            {
                <tr>
                    <td>@user.UserName</td>
                    <td>
                        <input type="checkbox" name="IdsToDelete" value="@user.Id" />
                    </td>
                </tr>
            }
           }
        </table>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    @Html.ActionLink("Cancel", "Index", null, new { @class="btn btn-default"})
}

TalmerMaint.WebUI/Views/RoleAdmin/Index.cshtml
@using TalmerMaint.Domain.Entities
@using TalmerMaint.WebUI.Infrastructure
@model IEnumerable<AppRole>
@{
    ViewBag.Title = "Roles Manager";
}

<h2>Roles Manager</h2>
@Html.ActionLink("Add Role", "Create", null, new { @class = "btn btn-default", style="margin-bottom:10px;"})
<table class="table table-striped">
    <tr>
        <th>Name</th>
        <th>Users</th>
        <th></th>
    </tr>
    @if (Model.Count() == 0)
    {
        <tr><td colspan="3" class="text-center">No Roles are Defined</td></tr>
    }
    else
    {
        foreach (AppRole role in Model)
        {
            <tr>
                <td>@role.Name</td>
                <td>
                    @if (role.Users == null || role.Users.Count == 0)
                    {
                        @:No users are in this role
                    }
                    else
                    {
                        /* for some reason the GetUserName function just hangs
                        <p>
                            
                            @string.Join(", ", role.Users.Select(x => Html.GetUserName(x.UserId)))
                        </p>
                        */
                    }

                    </td>
                <td>
                    @using (Html.BeginForm("Delete", "RoleAdmin", new { id = role.Id }))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = role.Id }, new { @class= "btn btn-primary btn-xs"})
                        <button class="btn btn-danger btn-xs" type="submit">Delete</button>
                    }
                </td>

            </tr>
    }
}
</table>